config/routes.rb
Rails.application.routes.draw do
  #TOPページ 
  root to: 'top#index'
  # コート数と人数のページ
  get '/setup', to: 'setup#index', as: 'setup'
  # メンバー詳細画面
  get '/setting', to: 'setting#index', as: 'setting'
  # play画面
  get '/play', to: 'play#index', as: 'play'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/play_controller.rb
class PlayController < ApplicationController
  def index
    #####
    # メンバー情報配列をシャッフルしたものを回戦数*12の数分つくる。それを４分割する。
    #####

    # コート数
    court = params[:coat].to_i
    # メンバー情報
    member = params[:info]
    # 回戦数
    round = params[:round].to_i
    # 必要人数
    total_count = round * (court * 4)
    # メンバー数に掛ける数
    multiplier = (total_count / member.length.to_f).ceil
    # 最終的な組み合わせ配列
    final_member_array = []

    # シャッフルしたメンバーリストをmultiplier分作ってfinal_member_arrayにまとめる
    for i in 1..multiplier
      shuffle_member_list = member.shuffle
      final_member_array = final_member_array + shuffle_member_list
    end

    # 回戦数分用意したメンバーリストを４分割する
    @split_member_array = final_member_array.in_groups_of(4, false)

  end
end

app/controllers/setting_controller.rb
class SettingController < ApplicationController
  def index
    @number_of_courts = params[:coat]
    @number_of_rounds = params[:number_of_rounds]
    @member_count = params[:member_count]
  end
end

app/controllers/setup_controller.rb
class SetupController < ApplicationController
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchOpen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/play/index.html.erb
<h1>組み合わせを発表します。</h1>

<% @split_member_array.each_with_index do |group, i| %>
  <div style="margin-bottom: 10px; border: 1px solid; padding: 10px;">
    <h3><%= i+1 %>戦目</h3>
    <% group.each_with_index do |member, i| %>
      <% if i == 0 || i == 1 %>
        <div style="display:flex; background-color:#FFA07A;">
          <p><%= member[:number] %>:</p>
          <p><%= member[:name] %></p>
        </div>
      <% else %>
        <div style="display:flex; background-color:#AFEEEE;">
          <p><%= member[:number] %>:</p>
          <p><%= member[:name] %></p>
        </div>
      <% end %>
     

      <% if false %>
        <% case member[:experience] %>
        <% when 2 then %>
            <p>経験者</p>
        <% when 1 then %>
            <p>ルール把握</p>
        <% else %>
            <p>未経験</p>
        <% end %>
      <% end %>

    <% end %>
  </div>
<% end %>


<%= link_to "戻る", setting_path %>
<%= link_to "TOPに戻る", root_path %>

app/views/setting/index.html.erb
<h1>参加者の情報を入力してください。</h1>

<%= form_tag(play_path, method: :get) do %>

  <%= hidden_field_tag :coat, @number_of_courts %>
  <%= hidden_field_tag :round, @number_of_rounds %>

  <div class="form">
    <div class="member_info">
      <% for i in 1..@member_count.to_i %>
        <div style="margin-top:10px; border:1px solid; padding: 5px">
          <p><%= i %>人目の情報</p>
          <%= hidden_field_tag "info[][number]", i %>
          <p>名前</p>
          <%= text_field_tag "info[][name]" %>
          <p>バドミントン経験</p>
          <%= select_tag 'info[][experience]', options_for_select({'未経験': 0, 'ルール把握': 1, '経験者': 2}, 0) %>
        </div>
      <% end  %>
    </div>
    <div style="margin-top:10px">
      <%= submit_tag '始める' %>
    </div>
  </div>

<% end %>

<div style="margin-top:10px">
  <%= link_to "戻る", setup_path %>
</div>

app/views/setup/index.html.erb
<h1>コート数と参加者数を入力してください。</h1>

<%= form_tag(setting_path, method: :get) do %>

  <p>コートの数は？</p>
  <%= select_tag 'coat', options_for_select({'1面': 1, '2面': 2, '3面': 3}, 1) %>

  <p>参加人数は？</p>
  <%= number_field_tag 'member_count', nil, in: 1...30%>

  <p>何回戦やりますか？</p>
  <%= number_field_tag 'number_of_rounds', nil, in: 1...30%>
  
  <%= submit_tag '次へ' %>
<% end %>

<%= link_to "戻る", root_path %>

app/views/top/index.html.erb
<h1>MatchOpen</h1>
<p>設定した参加者から４人組の組み合わせを作成します。</p>
<p>バドミントンやテニスのダブルスのペア作成に活用できます。</p>
<%= link_to "始める", setup_path %>